### ISSUE TITLE
ax25tools: make installconf: *** No rule to make target 'installconf'.

### ISSUE THREAD

**Issue by hobbes1069** [ve7fet/linuxax25#8]
Was the installconf target intentionally removed? It's still the the spec file...

**Comment by ve7fet** [comment]
Yup, see https://github.com/ve7fet/linuxax25/blob/master/ax25tools/ChangeLog. Default config files are now installed with .dist extensions, so they don't clobber working files.

I don't use any OS that uses the .spec file, so that file isn't maintained. It probably needs to be removed out of there, but then again, the whole .spec file probably needs to be updated too.
